version: '3.9'
services:
  yolo-api:
    image: yolo-api:latest
    container_name: yolo-api
    restart: "always"
    volumes:
    - ~/predicted:/app/predicted
    - ./:/app
    working_dir: /app
    ports:
      - "8001:8001"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001